In [2]:
import pandas as pd
from tqdm.notebook import tqdm

In [3]:

df_all = pd.read_csv("data/plEventsData.csv",low_memory=False)

pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

In [4]:
df_all[df_all['Unnamed: 0'] == 0]

,Unnamed: 0,id,eventId,minute,second,teamId,x,y,expandedMinute,qualifiers,satisfiedEventsTypes,isTouch,period_value,period_displayName,type_value,type_displayName,outcomeType_value,outcomeType_displayName,playerId,endX,endY,relatedEventId,relatedPlayerId,goalMouthZ,goalMouthY,isShot,blockedX,blockedY,cardType_value,cardType_displayName,isGoal,name,position,shirtNo,isOwnGoal
0,0,2.253487e+09,2,0,0.0,32,0.0,0.0,0,[],[],False,1,FirstHalf,32,Start,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1551,0,2.255910e+09,2,0,0.0,24,0.0,0.0,0,[],[],False,1,FirstHalf,32,Start,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3105,0,2.210296e+09,2,0,0.0,18,0.0,0.0,0,[],[],False,1,FirstHalf,32,Start,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4681,0,2.210244e+09,2,0,0.0,13,0.0,0.0,0,[],[],False,1,FirstHalf,32,Start,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6329,0,2.210493e+09,2,0,0.0,26,0.0,0.0,0,[],[],False,1,FirstHalf,32,Start,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599829,0,2.302209e+09,2,0,0.0,26,0.0,0.0,0,[],[],False,1,FirstHalf,32,Start,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
601314,0,2.302211e+09,2,0,0.0,167,0.0,0.0,0,[],[],False,1,FirstHalf,32,Start,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
602955,0,2.302211e+09,2,0,0.0,163,0.0,0.0,0,[],[],False,1,FirstHalf,32,Start,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
604575,0,2.302210e+09,2,0,0.0,29,0.0,0.0,0,[],[],False,1,FirstHalf,32,Start,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
606030,0,2.302210e+09,2,0,0.0,161,0.0,0.0,0,[],[],False,1,FirstHalf,32,Start,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
index = df_all[df_all['Unnamed: 0'] == 0].index

In [8]:
index

Int64Index([     0,   1551,   3105,   4681,   6329,   7992,   9730,  11251,
             12730,  14309,
            ...
            592020, 593719, 595222, 596723, 598170, 599829, 601314, 602955,
            604575, 606030],
           dtype='int64', length=380)

In [14]:
for i,idx in tqdm(enumerate(index[:-1])):
    df_all.iloc[idx:index[i+1]].to_csv("data/20_21/{}.csv".format(str(i)))
df_all.iloc[index[-1]:].to_csv("data/20_21/{}.csv".format(i+1))

0it [00:00, ?it/s]